//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 05/04/2012 01:55:47
namespace PerformanceMonitor
{
    
    /// <summary>
    /// There are no comments for Model2Container in the schema.
    /// </summary>
    public partial class Model2Container : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Model2Container object using the connection string found in the 'Model2Container' section of the application configuration file.
        /// </summary>
        public Model2Container() : 
                base("name=Model2Container", "Model2Container")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Model2Container object.
        /// </summary>
        public Model2Container(string connectionString) : 
                base(connectionString, "Model2Container")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Model2Container object.
        /// </summary>
        public Model2Container(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Model2Container")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
    }
}
